import { Sparkles, TrendingUp, AlertCircle, Lightbulb } from 'lucide-react';

interface InsightData {
    type: 'positive' | 'warning' | 'neutral';
    title: string;
    description: string;
}

interface AIInsightsSummaryProps {
    insights: InsightData[];
}

const AIInsightsSummary = ({ insights }: AIInsightsSummaryProps) => {
    const getIcon = (type: string) => {
        switch (type) {
            case 'positive':
                return <TrendingUp className="w-5 h-5 text-emerald-600" />;
            case 'warning':
                return <AlertCircle className="w-5 h-5 text-amber-600" />;
            default:
                return <Lightbulb className="w-5 h-5 text-blue-600" />;
        }
    };

    const getBorderColor = (type: string) => {
        switch (type) {
            case 'positive':
                return 'border-l-emerald-500';
            case 'warning':
                return 'border-l-amber-500';
            default:
                return 'border-l-blue-500';
        }
    };

    return (
        <div className="glass-card rounded-2xl shadow-2xl p-6 border-2 border-white/20">
            <div className="flex items-center space-x-3 mb-6">
                <div className="bg-gradient-to-br from-blue-500 to-cyan-500 p-2.5 rounded-xl shadow-lg">
                    <Sparkles className="w-6 h-6 text-white" />
                </div>
                <div>
                    <h2 className="text-2xl font-bold text-gray-900">Intelligence Insights</h2>
                    <p className="text-sm text-gray-600 font-medium">Smart analytics from your marketing data</p>
                </div>
            </div>

            <div className="space-y-3">
                {insights.length > 0 ? (
                    insights.map((insight, index) => (
                        <div
                            key={index}
                            className={`bg-white/90 backdrop-blur-sm rounded-xl p-4 border-l-4 ${getBorderColor(insight.type)} shadow-sm hover:shadow-md transition-all duration-200 hover:translate-x-1`}
                        >
                            <div className="flex items-start space-x-3">
                                <div className="flex-shrink-0 mt-0.5">
                                    {getIcon(insight.type)}
                                </div>
                                <div className="flex-1">
                                    <h3 className="text-base font-bold text-gray-900 mb-1">{insight.title}</h3>
                                    <p className="text-sm text-gray-700 leading-relaxed">{insight.description}</p>
                                </div>
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="text-center py-8 text-gray-500">
                        <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-30" />
                        <p className="text-sm">Analyzing data to generate insights...</p>
                    </div>
                )}
            </div>

            <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-cyan-50 rounded-xl border border-blue-200">
                <p className="text-xs text-gray-600 italic flex items-center space-x-2">
                    <Sparkles className="w-4 h-4 text-blue-600" />
                    <span>Generated by advanced AI analyzing your marketing performance metrics</span>
                </p>
            </div>
        </div>
    );
};

export default AIInsightsSummary;
